### ISSUE TITLE
FirebaseError: Firebase: Error (auth/invalid-api-key).

### ISSUE THREAD

**Issue by DonSenorSombrero** [MayorFalomo/Twitter-clone#3]
![Screenshot 2024-11-03 041128](https://github.com/user-attachments/assets/22a2ff56-8efc-4a36-9477-160203077ebd)

Every time i try to run it, this pops up, what could be the fix for it?

**Comment by MayorFalomo** [comment]
I think it's more polite to at least say Hello first no??

**Comment by DonSenorSombrero** [comment]
I'm so sorry, I was a bit of a rush lately so I wasn't able to

**Comment by MayorFalomo** [comment]
Alright that's fine.
So what the problem is probably is you've either not passed the an Api key
or you're passing the wrong Api_key.

Have you done either?

**Comment by DonSenorSombrero** [comment]
I've actually done neither. I was trying to run your code locally but it seems like I've probably done something wrong with the setup?

**Comment by MayorFalomo** [comment]
Yeah that’s probably it.
You’d need to add your all your necessary API keys.
Then when you’ve done that, you can install it.

Or have you figured it out already?

**Comment by DonSenorSombrero** [comment]
Yes, it seems like the problem were the missing API keys worked. Thank you so much. 
![Screenshot 2024-11-04 230347](https://github.com/user-attachments/assets/8973ae53-2ad9-453a-847e-ab5d45179fb6)
But there seems to be another issue that appeared, I'm guessing it's because I switched the firebase creds from the original one to another one to mine so that made the link unable to be found? or it's an entirely different problem.

**Comment by DonSenorSombrero** [comment]
Thank you very much, that helped. 
Aside from that, I find your work here in github to be really inspiring and helpful for me to learn how to code better because I'm a novice at programming XD so I'm thankful I get to see your own work from learning web development.

**Comment by DonSenorSombrero** [comment]
![Screenshot 2024-11-05 001806](https://github.com/user-attachments/assets/d149fa75-c08a-4eff-8ef5-05a9d2103890)

Seems like another problem appeared. I can give you more details if need be

**Comment by MayorFalomo** [comment]
Hi Don.
Alright can you send me the exact error message, and when does it pop up?
Can you send me the exact error message?

**Comment by MayorFalomo** [comment]
Glad you were able to fix it.
What’s the exact error for this one also and when does it happen?

**Comment by MayorFalomo** [comment]
I’m really glad to hear my work has helped you in a way even if it’s a bit,
it means a lot. 🫡
Kindly get back to me if you need help with running anything.

**Comment by DonSenorSombrero** [comment]
It happens immediately just when i open it locally. 
![Screenshot 2024-11-05 011624](https://github.com/user-attachments/assets/78645761-a2c6-4986-a7d5-3a1a964a6662)
`(node:17752) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17888) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - `compiler` options in `next.config.js` will be ignored while using Babel https://nextjs.org/docs/messages/ignored-compiler-options
info  - Using external babel configuration from C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\.babelrc
event - compiled client and server successfully in 4.7s (295 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 9.1s (841 modules)
wait  - compiling /[id] (client and server)...
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 3.2s (871 modules)
error - TypeError: Failed to parse URL from undefined/tweets/undefined
    at node:internal/deps/undici/undici:13392:13
    at async getServerSideProps (webpack-internal:///./pages/[id].tsx:99:15) {
  page: '/undefined',
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:816:29)
      at new Request (node:internal/deps/undici/undici:9474:25)
      at fetch (node:internal/deps/undici/undici:10203:25)
      at fetch (node:internal/deps/undici/undici:13390:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at getServerSideProps (webpack-internal:///./pages/[id].tsx:99:21)
      at C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\render.js:514:110
      at C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:66:32
      at NoopContextManager.with (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7054)
      at ContextAPI.with (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:517)
      at NoopTracer.startActiveSpan (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18022)
      at ProxyTracer.startActiveSpan (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18782)
      at runWithContext (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:60:164)
      at NextTracerImpl.trace (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:61:16)
      at Object.renderToHTML (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\render.js:514:51)
      at async doRender (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\base-server.js:810:34)
      at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\base-server.js:931:28)
      at async C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\response-cache\index.js:83:36 {
    code: 'ERR_INVALID_URL',
    input: 'undefined/tweets/undefined'
  }
}`

**Comment by MayorFalomo** [comment]
Did you already run npm install? be sure to already have Axios installed and all other dependencies.

**Comment by DonSenorSombrero** [comment]
Yep I have installed all the dependencies including axios. I also tried to install everything through yarn but that ended up with the same problem

**Comment by DonSenorSombrero** [comment]
`error - TypeError: Failed to parse URL from undefined/tweets/undefined
    at node:internal/deps/undici/undici:13392:13
    at async getServerSideProps (webpack-internal:///./pages/[id].tsx:99:15) {
  page: '/undefined',
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:816:29)
      at new Request (node:internal/deps/undici/undici:9474:25)
      at fetch (node:internal/deps/undici/undici:10203:25)
      at fetch (node:internal/deps/undici/undici:13390:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at getServerSideProps (webpack-internal:///./pages/[id].tsx:99:21)
      at C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\render.js:514:110
      at C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:66:32
      at NoopContextManager.with (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7054)
      at ContextAPI.with (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:517)
      at NoopTracer.startActiveSpan (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18022)
      at ProxyTracer.startActiveSpan (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18782)
      at runWithContext (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:60:164)
      at NextTracerImpl.trace (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\lib\trace\tracer.js:61:16)
      at Object.renderToHTML (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\render.js:514:51)
      at async doRender (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\base-server.js:810:34)
      at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\base-server.js:931:28)  
      at async C:\Users\user'\OneDrive\Desktop\twittest\Twitter-clone\node_modules\next\dist\server\response-cache\index.js:83:36 {
    code: 'ERR_INVALID_URL',
    input: 'undefined/tweets/undefined'
  }
}`

**Comment by DonSenorSombrero** [comment]
What do you think is a possible fix for this?

**Comment by MayorFalomo** [comment]
Of course it is...I'd need to take a more up-close look on how you ran
everything, since it all still works from my end.

**Comment by DonSenorSombrero** [comment]
I'm trying to run things through VS code, I could send you a zip of that file. Although I do wanna ask how do you run this yourself?  maybe i just missed something

**Comment by DonSenorSombrero** [comment]
I'm trying to run things through VS code, I could send you a zip of that
file. Although I do wanna ask how do you run this yourself locally if you
don't mind? maybe i just missed something during the npm install since I
know how things are sometimes a bit unreliable in vs code for me

**Comment by DonSenorSombrero** [comment]
or a copy of how you set up everthing? I'm slowly getting desperate lol your website seems to be the only one that works well enough here in github at the moment XD

**Comment by MayorFalomo** [comment]
@DonSenorSombrero Sorry for the late reply, I've been busy.
Anyway I run it just fine locally, everything still works, I usually don't have the time to update or check it anymore since it's a past project for me now, But I checked recently and saw certain folks decided to go wild with "testing" and broke the apps layout by causing it to overflow, cos i didn't account for somethings.

I've pushed fixes for that now and even another fix for modals that are supposed to open on tweets looking ugly, If you check the updates you can confirm this, That's all to tell you, everything still works fine from my end.

If you're facing issues, It has to be something you're not accounting for causing it.

**Comment by MayorFalomo** [comment]
Why are you getting desperate though, What's it to you? maybe I can help you better that way.
I've seen a couple other twitter websites that work, If they don't anymore it's probably cos the devs are too busy to maintain it.
